var annotated_dup =
[
    [ "webcface", "namespacewebcface.html", [
      [ "Common", "namespacewebcface_1_1Common.html", [
        [ "Arg", "classwebcface_1_1Common_1_1Arg.html", "classwebcface_1_1Common_1_1Arg" ],
        [ "Dict", "classwebcface_1_1Common_1_1Dict.html", "classwebcface_1_1Common_1_1Dict" ],
        [ "DictElement", "structwebcface_1_1Common_1_1DictElement.html", "structwebcface_1_1Common_1_1DictElement" ],
        [ "DictTraits", "structwebcface_1_1Common_1_1DictTraits.html", "structwebcface_1_1Common_1_1DictTraits" ],
        [ "DictTraits< std::shared_ptr< T > >", "structwebcface_1_1Common_1_1DictTraits_3_01std_1_1shared__ptr_3_01T_01_4_01_4.html", "structwebcface_1_1Common_1_1DictTraits_3_01std_1_1shared__ptr_3_01T_01_4_01_4" ],
        [ "DictTraits< VectorOpt< T > >", "structwebcface_1_1Common_1_1DictTraits_3_01VectorOpt_3_01T_01_4_01_4.html", "structwebcface_1_1Common_1_1DictTraits_3_01VectorOpt_3_01T_01_4_01_4" ],
        [ "FieldBase", "structwebcface_1_1Common_1_1FieldBase.html", "structwebcface_1_1Common_1_1FieldBase" ],
        [ "FieldBaseComparable", "structwebcface_1_1Common_1_1FieldBaseComparable.html", "structwebcface_1_1Common_1_1FieldBaseComparable" ],
        [ "FuncCall", "structwebcface_1_1Common_1_1FuncCall.html", "structwebcface_1_1Common_1_1FuncCall" ],
        [ "FuncInfo", "structwebcface_1_1Common_1_1FuncInfo.html", "structwebcface_1_1Common_1_1FuncInfo" ],
        [ "ImageBase", "classwebcface_1_1Common_1_1ImageBase.html", "classwebcface_1_1Common_1_1ImageBase" ],
        [ "ImageReq", "structwebcface_1_1Common_1_1ImageReq.html", "structwebcface_1_1Common_1_1ImageReq" ],
        [ "ImageWithCV", "classwebcface_1_1Common_1_1ImageWithCV.html", "classwebcface_1_1Common_1_1ImageWithCV" ],
        [ "LogLine", "structwebcface_1_1Common_1_1LogLine.html", "structwebcface_1_1Common_1_1LogLine" ],
        [ "Queue", "classwebcface_1_1Common_1_1Queue.html", "classwebcface_1_1Common_1_1Queue" ],
        [ "ValAdaptor", "classwebcface_1_1Common_1_1ValAdaptor.html", "classwebcface_1_1Common_1_1ValAdaptor" ],
        [ "VectorOpt", "structwebcface_1_1Common_1_1VectorOpt.html", "structwebcface_1_1Common_1_1VectorOpt" ],
        [ "VecTypeDisabled", "structwebcface_1_1Common_1_1VecTypeDisabled.html", null ],
        [ "ViewComponentBase", "structwebcface_1_1Common_1_1ViewComponentBase.html", "structwebcface_1_1Common_1_1ViewComponentBase" ]
      ] ],
      [ "Internal", "namespacewebcface_1_1Internal.html", [
        [ "SyncDataStore1", "classwebcface_1_1Internal_1_1SyncDataStore1.html", null ]
      ] ],
      [ "AnonymousFunc", "classwebcface_1_1AnonymousFunc.html", "classwebcface_1_1AnonymousFunc" ],
      [ "Arg", "classwebcface_1_1Common_1_1Arg.html", "classwebcface_1_1Common_1_1Arg" ],
      [ "AsyncFuncResult", "classwebcface_1_1AsyncFuncResult.html", "classwebcface_1_1AsyncFuncResult" ],
      [ "Client", "classwebcface_1_1Client.html", "classwebcface_1_1Client" ],
      [ "Dict", "classwebcface_1_1Common_1_1Dict.html", "classwebcface_1_1Common_1_1Dict" ],
      [ "DictElement", "structwebcface_1_1Common_1_1DictElement.html", "structwebcface_1_1Common_1_1DictElement" ],
      [ "DictTraits", "structwebcface_1_1Common_1_1DictTraits.html", "structwebcface_1_1Common_1_1DictTraits" ],
      [ "DictTraits< std::shared_ptr< T > >", "structwebcface_1_1Common_1_1DictTraits_3_01std_1_1shared__ptr_3_01T_01_4_01_4.html", "structwebcface_1_1Common_1_1DictTraits_3_01std_1_1shared__ptr_3_01T_01_4_01_4" ],
      [ "DictTraits< VectorOpt< T > >", "structwebcface_1_1Common_1_1DictTraits_3_01VectorOpt_3_01T_01_4_01_4.html", "structwebcface_1_1Common_1_1DictTraits_3_01VectorOpt_3_01T_01_4_01_4" ],
      [ "EventTarget", "classwebcface_1_1EventTarget.html", "classwebcface_1_1EventTarget" ],
      [ "Field", "structwebcface_1_1Field.html", "structwebcface_1_1Field" ],
      [ "FieldBase", "structwebcface_1_1Common_1_1FieldBase.html", "structwebcface_1_1Common_1_1FieldBase" ],
      [ "FieldBaseComparable", "structwebcface_1_1Common_1_1FieldBaseComparable.html", "structwebcface_1_1Common_1_1FieldBaseComparable" ],
      [ "Func", "classwebcface_1_1Func.html", "classwebcface_1_1Func" ],
      [ "FuncCall", "structwebcface_1_1Common_1_1FuncCall.html", "structwebcface_1_1Common_1_1FuncCall" ],
      [ "FuncInfo", "structwebcface_1_1Common_1_1FuncInfo.html", "structwebcface_1_1Common_1_1FuncInfo" ],
      [ "FuncNotFound", "structwebcface_1_1FuncNotFound.html", "structwebcface_1_1FuncNotFound" ],
      [ "Image", "classwebcface_1_1Image.html", "classwebcface_1_1Image" ],
      [ "ImageBase", "classwebcface_1_1Common_1_1ImageBase.html", "classwebcface_1_1Common_1_1ImageBase" ],
      [ "ImageReq", "structwebcface_1_1Common_1_1ImageReq.html", "structwebcface_1_1Common_1_1ImageReq" ],
      [ "ImageWithCV", "classwebcface_1_1Common_1_1ImageWithCV.html", "classwebcface_1_1Common_1_1ImageWithCV" ],
      [ "Log", "classwebcface_1_1Log.html", "classwebcface_1_1Log" ],
      [ "LoggerBuf", "classwebcface_1_1LoggerBuf.html", "classwebcface_1_1LoggerBuf" ],
      [ "LoggerSink", "classwebcface_1_1LoggerSink.html", "classwebcface_1_1LoggerSink" ],
      [ "LogLine", "structwebcface_1_1Common_1_1LogLine.html", "structwebcface_1_1Common_1_1LogLine" ],
      [ "Member", "classwebcface_1_1Member.html", "classwebcface_1_1Member" ],
      [ "Queue", "classwebcface_1_1Common_1_1Queue.html", "classwebcface_1_1Common_1_1Queue" ],
      [ "Text", "classwebcface_1_1Text.html", "classwebcface_1_1Text" ],
      [ "ValAdaptor", "classwebcface_1_1Common_1_1ValAdaptor.html", "classwebcface_1_1Common_1_1ValAdaptor" ],
      [ "Value", "classwebcface_1_1Value.html", "classwebcface_1_1Value" ],
      [ "VectorOpt", "structwebcface_1_1Common_1_1VectorOpt.html", "structwebcface_1_1Common_1_1VectorOpt" ],
      [ "VecTypeDisabled", "structwebcface_1_1Common_1_1VecTypeDisabled.html", null ],
      [ "View", "classwebcface_1_1View.html", "classwebcface_1_1View" ],
      [ "ViewBuf", "classwebcface_1_1ViewBuf.html", "classwebcface_1_1ViewBuf" ],
      [ "ViewComponent", "classwebcface_1_1ViewComponent.html", "classwebcface_1_1ViewComponent" ],
      [ "ViewComponentBase", "structwebcface_1_1Common_1_1ViewComponentBase.html", "structwebcface_1_1Common_1_1ViewComponentBase" ]
    ] ],
    [ "WEBCFACE_NS", "namespaceWEBCFACE__NS.html", [
      [ "Internal", "namespaceWEBCFACE__NS_1_1Internal.html", [
        [ "ClientData", "structWEBCFACE__NS_1_1Internal_1_1ClientData.html", "structWEBCFACE__NS_1_1Internal_1_1ClientData" ],
        [ "FuncOnSync", "classWEBCFACE__NS_1_1Internal_1_1FuncOnSync.html", "classWEBCFACE__NS_1_1Internal_1_1FuncOnSync" ],
        [ "FuncResultStore", "classWEBCFACE__NS_1_1Internal_1_1FuncResultStore.html", "classWEBCFACE__NS_1_1Internal_1_1FuncResultStore" ],
        [ "SyncDataStore1", "classWEBCFACE__NS_1_1Internal_1_1SyncDataStore1.html", "classWEBCFACE__NS_1_1Internal_1_1SyncDataStore1" ],
        [ "SyncDataStore2", "classWEBCFACE__NS_1_1Internal_1_1SyncDataStore2.html", "classWEBCFACE__NS_1_1Internal_1_1SyncDataStore2" ]
      ] ],
      [ "Message", "namespaceWEBCFACE__NS_1_1Message.html", [
        [ "Call", "structWEBCFACE__NS_1_1Message_1_1Call.html", "structWEBCFACE__NS_1_1Message_1_1Call" ],
        [ "CallResponse", "structWEBCFACE__NS_1_1Message_1_1CallResponse.html", "structWEBCFACE__NS_1_1Message_1_1CallResponse" ],
        [ "CallResult", "structWEBCFACE__NS_1_1Message_1_1CallResult.html", "structWEBCFACE__NS_1_1Message_1_1CallResult" ],
        [ "Entry", "structWEBCFACE__NS_1_1Message_1_1Entry.html", "structWEBCFACE__NS_1_1Message_1_1Entry" ],
        [ "FuncInfo", "structWEBCFACE__NS_1_1Message_1_1FuncInfo.html", "structWEBCFACE__NS_1_1Message_1_1FuncInfo" ],
        [ "Image", "structWEBCFACE__NS_1_1Message_1_1Image.html", "structWEBCFACE__NS_1_1Message_1_1Image" ],
        [ "Log", "structWEBCFACE__NS_1_1Message_1_1Log.html", "structWEBCFACE__NS_1_1Message_1_1Log" ],
        [ "LogReq", "structWEBCFACE__NS_1_1Message_1_1LogReq.html", "structWEBCFACE__NS_1_1Message_1_1LogReq" ],
        [ "MessageBase", "structWEBCFACE__NS_1_1Message_1_1MessageBase.html", "structWEBCFACE__NS_1_1Message_1_1MessageBase" ],
        [ "Ping", "structWEBCFACE__NS_1_1Message_1_1Ping.html", "structWEBCFACE__NS_1_1Message_1_1Ping" ],
        [ "PingStatus", "structWEBCFACE__NS_1_1Message_1_1PingStatus.html", "structWEBCFACE__NS_1_1Message_1_1PingStatus" ],
        [ "PingStatusReq", "structWEBCFACE__NS_1_1Message_1_1PingStatusReq.html", "structWEBCFACE__NS_1_1Message_1_1PingStatusReq" ],
        [ "Req", "structWEBCFACE__NS_1_1Message_1_1Req.html", "structWEBCFACE__NS_1_1Message_1_1Req" ],
        [ "Req< Image >", "structWEBCFACE__NS_1_1Message_1_1Req_3_01Image_01_4.html", "structWEBCFACE__NS_1_1Message_1_1Req_3_01Image_01_4" ],
        [ "Res", "structWEBCFACE__NS_1_1Message_1_1Res.html", null ],
        [ "Res< Image >", "structWEBCFACE__NS_1_1Message_1_1Res_3_01Image_01_4.html", "structWEBCFACE__NS_1_1Message_1_1Res_3_01Image_01_4" ],
        [ "Res< Text >", "structWEBCFACE__NS_1_1Message_1_1Res_3_01Text_01_4.html", "structWEBCFACE__NS_1_1Message_1_1Res_3_01Text_01_4" ],
        [ "Res< Value >", "structWEBCFACE__NS_1_1Message_1_1Res_3_01Value_01_4.html", "structWEBCFACE__NS_1_1Message_1_1Res_3_01Value_01_4" ],
        [ "Res< View >", "structWEBCFACE__NS_1_1Message_1_1Res_3_01View_01_4.html", "structWEBCFACE__NS_1_1Message_1_1Res_3_01View_01_4" ],
        [ "SvrVersion", "structWEBCFACE__NS_1_1Message_1_1SvrVersion.html", "structWEBCFACE__NS_1_1Message_1_1SvrVersion" ],
        [ "Sync", "structWEBCFACE__NS_1_1Message_1_1Sync.html", "structWEBCFACE__NS_1_1Message_1_1Sync" ],
        [ "SyncInit", "structWEBCFACE__NS_1_1Message_1_1SyncInit.html", "structWEBCFACE__NS_1_1Message_1_1SyncInit" ],
        [ "Text", "structWEBCFACE__NS_1_1Message_1_1Text.html", "structWEBCFACE__NS_1_1Message_1_1Text" ],
        [ "Value", "structWEBCFACE__NS_1_1Message_1_1Value.html", "structWEBCFACE__NS_1_1Message_1_1Value" ],
        [ "View", "structWEBCFACE__NS_1_1Message_1_1View.html", "structWEBCFACE__NS_1_1Message_1_1View" ]
      ] ],
      [ "Server", "namespaceWEBCFACE__NS_1_1Server.html", [
        [ "ClientData", "structWEBCFACE__NS_1_1Server_1_1ClientData.html", "structWEBCFACE__NS_1_1Server_1_1ClientData" ],
        [ "CustomLogger", "classWEBCFACE__NS_1_1Server_1_1CustomLogger.html", "classWEBCFACE__NS_1_1Server_1_1CustomLogger" ],
        [ "Store", "structWEBCFACE__NS_1_1Server_1_1Store.html", "structWEBCFACE__NS_1_1Server_1_1Store" ]
      ] ]
    ] ]
];