var annotated_dup =
[
    [ "webcface", "namespacewebcface.html", [
      [ "c_wcf", "namespacewebcface_1_1c__wcf.html", [
        [ "CharType", "structwebcface_1_1c__wcf_1_1CharType.html", null ],
        [ "CharType< char >", "structwebcface_1_1c__wcf_1_1CharType_3_01char_01_4.html", "structwebcface_1_1c__wcf_1_1CharType_3_01char_01_4" ],
        [ "CharType< wchar_t >", "structwebcface_1_1c__wcf_1_1CharType_3_01wchar__t_01_4.html", "structwebcface_1_1c__wcf_1_1CharType_3_01wchar__t_01_4" ]
      ] ],
      [ "components", "namespacewebcface_1_1components.html", [
        [ "geometries", "namespacewebcface_1_1components_1_1geometries.html", [
          [ "Box", "structwebcface_1_1components_1_1geometries_1_1Box.html", "structwebcface_1_1components_1_1geometries_1_1Box" ],
          [ "Circle", "structwebcface_1_1components_1_1geometries_1_1Circle.html", "structwebcface_1_1components_1_1geometries_1_1Circle" ],
          [ "Cylinder", "structwebcface_1_1components_1_1geometries_1_1Cylinder.html", "structwebcface_1_1components_1_1geometries_1_1Cylinder" ],
          [ "Line", "structwebcface_1_1components_1_1geometries_1_1Line.html", "structwebcface_1_1components_1_1geometries_1_1Line" ],
          [ "Plane", "structwebcface_1_1components_1_1geometries_1_1Plane.html", "structwebcface_1_1components_1_1geometries_1_1Plane" ],
          [ "Polygon", "structwebcface_1_1components_1_1geometries_1_1Polygon.html", "structwebcface_1_1components_1_1geometries_1_1Polygon" ],
          [ "Sphere", "structwebcface_1_1components_1_1geometries_1_1Sphere.html", "structwebcface_1_1components_1_1geometries_1_1Sphere" ]
        ] ],
        [ "Box", "structwebcface_1_1components_1_1geometries_1_1Box.html", "structwebcface_1_1components_1_1geometries_1_1Box" ],
        [ "Circle", "structwebcface_1_1components_1_1geometries_1_1Circle.html", "structwebcface_1_1components_1_1geometries_1_1Circle" ],
        [ "Cylinder", "structwebcface_1_1components_1_1geometries_1_1Cylinder.html", "structwebcface_1_1components_1_1geometries_1_1Cylinder" ],
        [ "Line", "structwebcface_1_1components_1_1geometries_1_1Line.html", "structwebcface_1_1components_1_1geometries_1_1Line" ],
        [ "Plane", "structwebcface_1_1components_1_1geometries_1_1Plane.html", "structwebcface_1_1components_1_1geometries_1_1Plane" ],
        [ "Polygon", "structwebcface_1_1components_1_1geometries_1_1Polygon.html", "structwebcface_1_1components_1_1geometries_1_1Polygon" ],
        [ "Sphere", "structwebcface_1_1components_1_1geometries_1_1Sphere.html", "structwebcface_1_1components_1_1geometries_1_1Sphere" ]
      ] ],
      [ "encoding", "namespacewebcface_1_1encoding.html", [
        [ "SharedString", "classwebcface_1_1encoding_1_1SharedString.html", "classwebcface_1_1encoding_1_1SharedString" ],
        [ "ValAdaptor", "classwebcface_1_1encoding_1_1ValAdaptor.html", "classwebcface_1_1encoding_1_1ValAdaptor" ]
      ] ],
      [ "geometries", "namespacewebcface_1_1components_1_1geometries.html", [
        [ "Box", "structwebcface_1_1components_1_1geometries_1_1Box.html", "structwebcface_1_1components_1_1geometries_1_1Box" ],
        [ "Circle", "structwebcface_1_1components_1_1geometries_1_1Circle.html", "structwebcface_1_1components_1_1geometries_1_1Circle" ],
        [ "Cylinder", "structwebcface_1_1components_1_1geometries_1_1Cylinder.html", "structwebcface_1_1components_1_1geometries_1_1Cylinder" ],
        [ "Line", "structwebcface_1_1components_1_1geometries_1_1Line.html", "structwebcface_1_1components_1_1geometries_1_1Line" ],
        [ "Plane", "structwebcface_1_1components_1_1geometries_1_1Plane.html", "structwebcface_1_1components_1_1geometries_1_1Plane" ],
        [ "Polygon", "structwebcface_1_1components_1_1geometries_1_1Polygon.html", "structwebcface_1_1components_1_1geometries_1_1Polygon" ],
        [ "Sphere", "structwebcface_1_1components_1_1geometries_1_1Sphere.html", "structwebcface_1_1components_1_1geometries_1_1Sphere" ]
      ] ],
      [ "internal", "namespacewebcface_1_1internal.html", [
        [ "Canvas2DComponentData", "structwebcface_1_1internal_1_1Canvas2DComponentData.html", "structwebcface_1_1internal_1_1Canvas2DComponentData" ],
        [ "Canvas2DDataBase", "structwebcface_1_1internal_1_1Canvas2DDataBase.html", "structwebcface_1_1internal_1_1Canvas2DDataBase" ],
        [ "Canvas2DDataBuf", "classwebcface_1_1internal_1_1Canvas2DDataBuf.html", "classwebcface_1_1internal_1_1Canvas2DDataBuf" ],
        [ "Canvas3DComponentData", "structwebcface_1_1internal_1_1Canvas3DComponentData.html", "structwebcface_1_1internal_1_1Canvas3DComponentData" ],
        [ "ClientData", "structwebcface_1_1internal_1_1ClientData.html", "structwebcface_1_1internal_1_1ClientData" ],
        [ "DataSetBuffer", "classwebcface_1_1internal_1_1DataSetBuffer.html", "classwebcface_1_1internal_1_1DataSetBuffer" ],
        [ "FuncInfo", "structwebcface_1_1internal_1_1FuncInfo.html", "structwebcface_1_1internal_1_1FuncInfo" ],
        [ "FuncResultStore", "classwebcface_1_1internal_1_1FuncResultStore.html", "classwebcface_1_1internal_1_1FuncResultStore" ],
        [ "InputRefState", "structwebcface_1_1internal_1_1InputRefState.html", "structwebcface_1_1internal_1_1InputRefState" ],
        [ "PromiseData", "structwebcface_1_1internal_1_1PromiseData.html", "structwebcface_1_1internal_1_1PromiseData" ],
        [ "RobotLinkData", "structwebcface_1_1internal_1_1RobotLinkData.html", "structwebcface_1_1internal_1_1RobotLinkData" ],
        [ "SharedStringData", "structwebcface_1_1internal_1_1SharedStringData.html", "structwebcface_1_1internal_1_1SharedStringData" ],
        [ "SyncDataStore1", "classwebcface_1_1internal_1_1SyncDataStore1.html", "classwebcface_1_1internal_1_1SyncDataStore1" ],
        [ "SyncDataStore2", "classwebcface_1_1internal_1_1SyncDataStore2.html", "classwebcface_1_1internal_1_1SyncDataStore2" ],
        [ "TemporalRobotJointData", "structwebcface_1_1internal_1_1TemporalRobotJointData.html", "structwebcface_1_1internal_1_1TemporalRobotJointData" ],
        [ "ViewBuf", "classwebcface_1_1internal_1_1ViewBuf.html", "classwebcface_1_1internal_1_1ViewBuf" ],
        [ "ViewComponentData", "structwebcface_1_1internal_1_1ViewComponentData.html", "structwebcface_1_1internal_1_1ViewComponentData" ]
      ] ],
      [ "message", "namespacewebcface_1_1message.html", [
        [ "Arg", "structwebcface_1_1message_1_1Arg.html", "structwebcface_1_1message_1_1Arg" ],
        [ "Call", "structwebcface_1_1message_1_1Call.html", "structwebcface_1_1message_1_1Call" ],
        [ "CallResponse", "structwebcface_1_1message_1_1CallResponse.html", "structwebcface_1_1message_1_1CallResponse" ],
        [ "CallResult", "structwebcface_1_1message_1_1CallResult.html", "structwebcface_1_1message_1_1CallResult" ],
        [ "Canvas2D", "structwebcface_1_1message_1_1Canvas2D.html", "structwebcface_1_1message_1_1Canvas2D" ],
        [ "Canvas2DComponent", "structwebcface_1_1message_1_1Canvas2DComponent.html", "structwebcface_1_1message_1_1Canvas2DComponent" ],
        [ "Canvas2DData", "structwebcface_1_1message_1_1Canvas2DData.html", "structwebcface_1_1message_1_1Canvas2DData" ],
        [ "Canvas3D", "structwebcface_1_1message_1_1Canvas3D.html", "structwebcface_1_1message_1_1Canvas3D" ],
        [ "Canvas3DComponent", "structwebcface_1_1message_1_1Canvas3DComponent.html", "structwebcface_1_1message_1_1Canvas3DComponent" ],
        [ "Entry", "structwebcface_1_1message_1_1Entry.html", "structwebcface_1_1message_1_1Entry" ],
        [ "FuncInfo", "structwebcface_1_1message_1_1FuncInfo.html", "structwebcface_1_1message_1_1FuncInfo" ],
        [ "Image", "structwebcface_1_1message_1_1Image.html", "structwebcface_1_1message_1_1Image" ],
        [ "ImageFrame", "structwebcface_1_1message_1_1ImageFrame.html", "structwebcface_1_1message_1_1ImageFrame" ],
        [ "ImageReq", "structwebcface_1_1message_1_1ImageReq.html", "structwebcface_1_1message_1_1ImageReq" ],
        [ "Log", "structwebcface_1_1message_1_1Log.html", "structwebcface_1_1message_1_1Log" ],
        [ "LogEntry", "structwebcface_1_1message_1_1LogEntry.html", "structwebcface_1_1message_1_1LogEntry" ],
        [ "LogLine", "structwebcface_1_1message_1_1LogLine.html", "structwebcface_1_1message_1_1LogLine" ],
        [ "LogReq", "structwebcface_1_1message_1_1LogReq.html", "structwebcface_1_1message_1_1LogReq" ],
        [ "MessageBase", "structwebcface_1_1message_1_1MessageBase.html", "structwebcface_1_1message_1_1MessageBase" ],
        [ "Ping", "structwebcface_1_1message_1_1Ping.html", "structwebcface_1_1message_1_1Ping" ],
        [ "PingStatus", "structwebcface_1_1message_1_1PingStatus.html", "structwebcface_1_1message_1_1PingStatus" ],
        [ "PingStatusReq", "structwebcface_1_1message_1_1PingStatusReq.html", "structwebcface_1_1message_1_1PingStatusReq" ],
        [ "Req", "structwebcface_1_1message_1_1Req.html", "structwebcface_1_1message_1_1Req" ],
        [ "Req< Image >", "structwebcface_1_1message_1_1Req_3_01Image_01_4.html", "structwebcface_1_1message_1_1Req_3_01Image_01_4" ],
        [ "Res", "structwebcface_1_1message_1_1Res.html", null ],
        [ "Res< Canvas2D >", "structwebcface_1_1message_1_1Res_3_01Canvas2D_01_4.html", "structwebcface_1_1message_1_1Res_3_01Canvas2D_01_4" ],
        [ "Res< Canvas3D >", "structwebcface_1_1message_1_1Res_3_01Canvas3D_01_4.html", "structwebcface_1_1message_1_1Res_3_01Canvas3D_01_4" ],
        [ "Res< Image >", "structwebcface_1_1message_1_1Res_3_01Image_01_4.html", "structwebcface_1_1message_1_1Res_3_01Image_01_4" ],
        [ "Res< RobotModel >", "structwebcface_1_1message_1_1Res_3_01RobotModel_01_4.html", "structwebcface_1_1message_1_1Res_3_01RobotModel_01_4" ],
        [ "Res< Text >", "structwebcface_1_1message_1_1Res_3_01Text_01_4.html", "structwebcface_1_1message_1_1Res_3_01Text_01_4" ],
        [ "Res< Value >", "structwebcface_1_1message_1_1Res_3_01Value_01_4.html", "structwebcface_1_1message_1_1Res_3_01Value_01_4" ],
        [ "Res< View >", "structwebcface_1_1message_1_1Res_3_01View_01_4.html", "structwebcface_1_1message_1_1Res_3_01View_01_4" ],
        [ "RobotLink", "structwebcface_1_1message_1_1RobotLink.html", "structwebcface_1_1message_1_1RobotLink" ],
        [ "RobotModel", "structwebcface_1_1message_1_1RobotModel.html", "structwebcface_1_1message_1_1RobotModel" ],
        [ "Sync", "structwebcface_1_1message_1_1Sync.html", "structwebcface_1_1message_1_1Sync" ],
        [ "SyncInit", "structwebcface_1_1message_1_1SyncInit.html", "structwebcface_1_1message_1_1SyncInit" ],
        [ "SyncInitEnd", "structwebcface_1_1message_1_1SyncInitEnd.html", "structwebcface_1_1message_1_1SyncInitEnd" ],
        [ "Text", "structwebcface_1_1message_1_1Text.html", "structwebcface_1_1message_1_1Text" ],
        [ "Value", "structwebcface_1_1message_1_1Value.html", "structwebcface_1_1message_1_1Value" ],
        [ "View", "structwebcface_1_1message_1_1View.html", "structwebcface_1_1message_1_1View" ],
        [ "ViewComponent", "structwebcface_1_1message_1_1ViewComponent.html", "structwebcface_1_1message_1_1ViewComponent" ]
      ] ],
      [ "server", "namespacewebcface_1_1server.html", [
        [ "AppWrapper", "classwebcface_1_1server_1_1AppWrapper.html", "classwebcface_1_1server_1_1AppWrapper" ],
        [ "CustomLogger", "classwebcface_1_1server_1_1CustomLogger.html", "classwebcface_1_1server_1_1CustomLogger" ],
        [ "MemberData", "structwebcface_1_1server_1_1MemberData.html", "structwebcface_1_1server_1_1MemberData" ],
        [ "Server", "classwebcface_1_1server_1_1Server.html", "classwebcface_1_1server_1_1Server" ],
        [ "ServerStorage", "classwebcface_1_1server_1_1ServerStorage.html", "classwebcface_1_1server_1_1ServerStorage" ]
      ] ],
      [ "AnonymousFunc", "classwebcface_1_1AnonymousFunc.html", "classwebcface_1_1AnonymousFunc" ],
      [ "Arg", "classwebcface_1_1Arg.html", "classwebcface_1_1Arg" ],
      [ "BasicLoggerBuf", "classwebcface_1_1BasicLoggerBuf.html", "classwebcface_1_1BasicLoggerBuf" ],
      [ "Box", "structwebcface_1_1components_1_1geometries_1_1Box.html", "structwebcface_1_1components_1_1geometries_1_1Box" ],
      [ "CallHandle", "classwebcface_1_1CallHandle.html", "classwebcface_1_1CallHandle" ],
      [ "Canvas2D", "classwebcface_1_1Canvas2D.html", "classwebcface_1_1Canvas2D" ],
      [ "Canvas2DComponent", "classwebcface_1_1Canvas2DComponent.html", "classwebcface_1_1Canvas2DComponent" ],
      [ "Canvas3D", "classwebcface_1_1Canvas3D.html", "classwebcface_1_1Canvas3D" ],
      [ "Canvas3DComponent", "classwebcface_1_1Canvas3DComponent.html", "classwebcface_1_1Canvas3DComponent" ],
      [ "CharType", "structwebcface_1_1c__wcf_1_1CharType.html", null ],
      [ "CharType< char >", "structwebcface_1_1c__wcf_1_1CharType_3_01char_01_4.html", "structwebcface_1_1c__wcf_1_1CharType_3_01char_01_4" ],
      [ "CharType< wchar_t >", "structwebcface_1_1c__wcf_1_1CharType_3_01wchar__t_01_4.html", "structwebcface_1_1c__wcf_1_1CharType_3_01wchar__t_01_4" ],
      [ "Circle", "structwebcface_1_1components_1_1geometries_1_1Circle.html", "structwebcface_1_1components_1_1geometries_1_1Circle" ],
      [ "Client", "classwebcface_1_1Client.html", "classwebcface_1_1Client" ],
      [ "Cylinder", "structwebcface_1_1components_1_1geometries_1_1Cylinder.html", "structwebcface_1_1components_1_1geometries_1_1Cylinder" ],
      [ "Field", "structwebcface_1_1Field.html", "structwebcface_1_1Field" ],
      [ "FieldBase", "structwebcface_1_1FieldBase.html", "structwebcface_1_1FieldBase" ],
      [ "Func", "classwebcface_1_1Func.html", "classwebcface_1_1Func" ],
      [ "FuncArgTypeCheck", "structwebcface_1_1FuncArgTypeCheck.html", null ],
      [ "FuncArgTypeCheck< true >", "structwebcface_1_1FuncArgTypeCheck_3_01true_01_4.html", "structwebcface_1_1FuncArgTypeCheck_3_01true_01_4" ],
      [ "FuncArgTypesTrait", "structwebcface_1_1FuncArgTypesTrait.html", null ],
      [ "FuncListener", "classwebcface_1_1FuncListener.html", "classwebcface_1_1FuncListener" ],
      [ "FuncNotFound", "structwebcface_1_1FuncNotFound.html", "structwebcface_1_1FuncNotFound" ],
      [ "FuncReturnTypeCheck", "structwebcface_1_1FuncReturnTypeCheck.html", null ],
      [ "FuncReturnTypeCheck< true >", "structwebcface_1_1FuncReturnTypeCheck_3_01true_01_4.html", "structwebcface_1_1FuncReturnTypeCheck_3_01true_01_4" ],
      [ "FuncReturnTypeTrait", "structwebcface_1_1FuncReturnTypeTrait.html", null ],
      [ "FuncSignatureTrait", "structwebcface_1_1FuncSignatureTrait.html", null ],
      [ "FuncSignatureTrait< Ret(*)(Args...)>", "structwebcface_1_1FuncSignatureTrait_3_01Ret_07_5_08_07Args_8_8_8_08_4.html", "structwebcface_1_1FuncSignatureTrait_3_01Ret_07_5_08_07Args_8_8_8_08_4" ],
      [ "FuncSignatureTrait< Ret(Args...)>", "structwebcface_1_1FuncSignatureTrait_3_01Ret_07Args_8_8_8_08_4.html", "structwebcface_1_1FuncSignatureTrait_3_01Ret_07Args_8_8_8_08_4" ],
      [ "FuncSignatureTrait< Ret(T::*)(Args...) const >", "structwebcface_1_1FuncSignatureTrait_3_01Ret_07T_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", "structwebcface_1_1FuncSignatureTrait_3_01Ret_07T_1_1_5_08_07Args_8_8_8_08_01const_01_4" ],
      [ "FuncSignatureTrait< Ret(T::*)(Args...)>", "structwebcface_1_1FuncSignatureTrait_3_01Ret_07T_1_1_5_08_07Args_8_8_8_08_4.html", "structwebcface_1_1FuncSignatureTrait_3_01Ret_07T_1_1_5_08_07Args_8_8_8_08_4" ],
      [ "Geometry", "structwebcface_1_1Geometry.html", "structwebcface_1_1Geometry" ],
      [ "Image", "classwebcface_1_1Image.html", "classwebcface_1_1Image" ],
      [ "ImageFrame", "classwebcface_1_1ImageFrame.html", "classwebcface_1_1ImageFrame" ],
      [ "InputRef", "classwebcface_1_1InputRef.html", "classwebcface_1_1InputRef" ],
      [ "Line", "structwebcface_1_1components_1_1geometries_1_1Line.html", "structwebcface_1_1components_1_1geometries_1_1Line" ],
      [ "Log", "classwebcface_1_1Log.html", "classwebcface_1_1Log" ],
      [ "LogLine", "classwebcface_1_1LogLine.html", "classwebcface_1_1LogLine" ],
      [ "LogLineData", "structwebcface_1_1LogLineData.html", "structwebcface_1_1LogLineData" ],
      [ "LogLineW", "classwebcface_1_1LogLineW.html", "classwebcface_1_1LogLineW" ],
      [ "Member", "classwebcface_1_1Member.html", "classwebcface_1_1Member" ],
      [ "Plane", "structwebcface_1_1components_1_1geometries_1_1Plane.html", "structwebcface_1_1components_1_1geometries_1_1Plane" ],
      [ "Point", "classwebcface_1_1Point.html", "classwebcface_1_1Point" ],
      [ "Polygon", "structwebcface_1_1components_1_1geometries_1_1Polygon.html", "structwebcface_1_1components_1_1geometries_1_1Polygon" ],
      [ "Promise", "classwebcface_1_1Promise.html", "classwebcface_1_1Promise" ],
      [ "Queue", "classwebcface_1_1Queue.html", "classwebcface_1_1Queue" ],
      [ "RobotJoint", "classwebcface_1_1RobotJoint.html", "classwebcface_1_1RobotJoint" ],
      [ "RobotLink", "classwebcface_1_1RobotLink.html", "classwebcface_1_1RobotLink" ],
      [ "RobotModel", "classwebcface_1_1RobotModel.html", "classwebcface_1_1RobotModel" ],
      [ "ScopedUnlock", "structwebcface_1_1ScopedUnlock.html", "structwebcface_1_1ScopedUnlock" ],
      [ "SharedString", "classwebcface_1_1encoding_1_1SharedString.html", "classwebcface_1_1encoding_1_1SharedString" ],
      [ "Size", "classwebcface_1_1Size.html", "classwebcface_1_1Size" ],
      [ "SizeOption", "classwebcface_1_1SizeOption.html", "classwebcface_1_1SizeOption" ],
      [ "Sphere", "structwebcface_1_1components_1_1geometries_1_1Sphere.html", "structwebcface_1_1components_1_1geometries_1_1Sphere" ],
      [ "TemporalCanvas2DComponent", "classwebcface_1_1TemporalCanvas2DComponent.html", "classwebcface_1_1TemporalCanvas2DComponent" ],
      [ "TemporalCanvas3DComponent", "classwebcface_1_1TemporalCanvas3DComponent.html", "classwebcface_1_1TemporalCanvas3DComponent" ],
      [ "TemporalComponent", "structwebcface_1_1TemporalComponent.html", "structwebcface_1_1TemporalComponent" ],
      [ "TemporalGeometry", "classwebcface_1_1TemporalGeometry.html", "classwebcface_1_1TemporalGeometry" ],
      [ "TemporalViewComponent", "classwebcface_1_1TemporalViewComponent.html", "classwebcface_1_1TemporalViewComponent" ],
      [ "Text", "classwebcface_1_1Text.html", "classwebcface_1_1Text" ],
      [ "Transform", "classwebcface_1_1Transform.html", "classwebcface_1_1Transform" ],
      [ "ValAdaptor", "classwebcface_1_1encoding_1_1ValAdaptor.html", "classwebcface_1_1encoding_1_1ValAdaptor" ],
      [ "Value", "classwebcface_1_1Value.html", "classwebcface_1_1Value" ],
      [ "Variant", "classwebcface_1_1Variant.html", "classwebcface_1_1Variant" ],
      [ "View", "classwebcface_1_1View.html", "classwebcface_1_1View" ],
      [ "ViewComponent", "classwebcface_1_1ViewComponent.html", "classwebcface_1_1ViewComponent" ]
    ] ],
    [ "wcfFuncCallHandle", "structwcfFuncCallHandle.html", "structwcfFuncCallHandle" ],
    [ "wcfFuncCallHandleW", "structwcfFuncCallHandleW.html", "structwcfFuncCallHandleW" ],
    [ "wcfMultiVal", "structwcfMultiVal.html", "structwcfMultiVal" ],
    [ "wcfMultiValW", "structwcfMultiValW.html", "structwcfMultiValW" ],
    [ "wcfViewComponent", "structwcfViewComponent.html", "structwcfViewComponent" ],
    [ "wcfViewComponentW", "structwcfViewComponentW.html", "structwcfViewComponentW" ]
];