var annotated_dup =
[
    [ "docstring", "namespacedocstring.html", [
      [ "PyClass", "classdocstring_1_1PyClass.html", "classdocstring_1_1PyClass" ]
    ] ],
    [ "pyexample", "namespacepyexample.html", [
      [ "PyClass", "classpyexample_1_1PyClass.html", "classpyexample_1_1PyClass" ]
    ] ],
    [ "WebCFace", "namespaceWebCFace.html", [
      [ "Common", "namespaceWebCFace_1_1Common.html", [
        [ "Arg", "classWebCFace_1_1Common_1_1Arg.html", "classWebCFace_1_1Common_1_1Arg" ],
        [ "Dict", "classWebCFace_1_1Common_1_1Dict.html", "classWebCFace_1_1Common_1_1Dict" ],
        [ "DictElement", "structWebCFace_1_1Common_1_1DictElement.html", "structWebCFace_1_1Common_1_1DictElement" ],
        [ "DictTraits", "structWebCFace_1_1Common_1_1DictTraits.html", "structWebCFace_1_1Common_1_1DictTraits" ],
        [ "DictTraits< std::shared_ptr< T > >", "structWebCFace_1_1Common_1_1DictTraits_3_01std_1_1shared__ptr_3_01T_01_4_01_4.html", "structWebCFace_1_1Common_1_1DictTraits_3_01std_1_1shared__ptr_3_01T_01_4_01_4" ],
        [ "DictTraits< VectorOpt< T > >", "structWebCFace_1_1Common_1_1DictTraits_3_01VectorOpt_3_01T_01_4_01_4.html", "structWebCFace_1_1Common_1_1DictTraits_3_01VectorOpt_3_01T_01_4_01_4" ],
        [ "FieldBase", "structWebCFace_1_1Common_1_1FieldBase.html", "structWebCFace_1_1Common_1_1FieldBase" ],
        [ "FieldBaseComparable", "structWebCFace_1_1Common_1_1FieldBaseComparable.html", "structWebCFace_1_1Common_1_1FieldBaseComparable" ],
        [ "FuncCall", "structWebCFace_1_1Common_1_1FuncCall.html", "structWebCFace_1_1Common_1_1FuncCall" ],
        [ "FuncInfo", "structWebCFace_1_1Common_1_1FuncInfo.html", "structWebCFace_1_1Common_1_1FuncInfo" ],
        [ "LogLine", "structWebCFace_1_1Common_1_1LogLine.html", "structWebCFace_1_1Common_1_1LogLine" ],
        [ "Queue", "classWebCFace_1_1Common_1_1Queue.html", "classWebCFace_1_1Common_1_1Queue" ],
        [ "ValAdaptor", "classWebCFace_1_1Common_1_1ValAdaptor.html", "classWebCFace_1_1Common_1_1ValAdaptor" ],
        [ "VectorOpt", "structWebCFace_1_1Common_1_1VectorOpt.html", "structWebCFace_1_1Common_1_1VectorOpt" ],
        [ "ViewComponentBase", "structWebCFace_1_1Common_1_1ViewComponentBase.html", "structWebCFace_1_1Common_1_1ViewComponentBase" ]
      ] ],
      [ "Message", "namespaceWebCFace_1_1Message.html", [
        [ "Call", "structWebCFace_1_1Message_1_1Call.html", "structWebCFace_1_1Message_1_1Call" ],
        [ "CallResponse", "structWebCFace_1_1Message_1_1CallResponse.html", "structWebCFace_1_1Message_1_1CallResponse" ],
        [ "CallResult", "structWebCFace_1_1Message_1_1CallResult.html", "structWebCFace_1_1Message_1_1CallResult" ],
        [ "Entry", "structWebCFace_1_1Message_1_1Entry.html", "structWebCFace_1_1Message_1_1Entry" ],
        [ "FuncInfo", "structWebCFace_1_1Message_1_1FuncInfo.html", "structWebCFace_1_1Message_1_1FuncInfo" ],
        [ "Log", "structWebCFace_1_1Message_1_1Log.html", "structWebCFace_1_1Message_1_1Log" ],
        [ "LogReq", "structWebCFace_1_1Message_1_1LogReq.html", "structWebCFace_1_1Message_1_1LogReq" ],
        [ "MessageBase", "structWebCFace_1_1Message_1_1MessageBase.html", null ],
        [ "Ping", "structWebCFace_1_1Message_1_1Ping.html", "structWebCFace_1_1Message_1_1Ping" ],
        [ "PingStatus", "structWebCFace_1_1Message_1_1PingStatus.html", "structWebCFace_1_1Message_1_1PingStatus" ],
        [ "PingStatusReq", "structWebCFace_1_1Message_1_1PingStatusReq.html", "structWebCFace_1_1Message_1_1PingStatusReq" ],
        [ "Req", "structWebCFace_1_1Message_1_1Req.html", "structWebCFace_1_1Message_1_1Req" ],
        [ "Res", "structWebCFace_1_1Message_1_1Res.html", null ],
        [ "Res< Text >", "structWebCFace_1_1Message_1_1Res_3_01Text_01_4.html", "structWebCFace_1_1Message_1_1Res_3_01Text_01_4" ],
        [ "Res< Value >", "structWebCFace_1_1Message_1_1Res_3_01Value_01_4.html", "structWebCFace_1_1Message_1_1Res_3_01Value_01_4" ],
        [ "Res< View >", "structWebCFace_1_1Message_1_1Res_3_01View_01_4.html", "structWebCFace_1_1Message_1_1Res_3_01View_01_4" ],
        [ "SvrVersion", "structWebCFace_1_1Message_1_1SvrVersion.html", "structWebCFace_1_1Message_1_1SvrVersion" ],
        [ "Sync", "structWebCFace_1_1Message_1_1Sync.html", "structWebCFace_1_1Message_1_1Sync" ],
        [ "SyncInit", "structWebCFace_1_1Message_1_1SyncInit.html", "structWebCFace_1_1Message_1_1SyncInit" ],
        [ "Text", "structWebCFace_1_1Message_1_1Text.html", "structWebCFace_1_1Message_1_1Text" ],
        [ "Value", "structWebCFace_1_1Message_1_1Value.html", "structWebCFace_1_1Message_1_1Value" ],
        [ "View", "structWebCFace_1_1Message_1_1View.html", "structWebCFace_1_1Message_1_1View" ]
      ] ],
      [ "Server", "namespaceWebCFace_1_1Server.html", [
        [ "ClientData", "structWebCFace_1_1Server_1_1ClientData.html", "structWebCFace_1_1Server_1_1ClientData" ],
        [ "Store", "structWebCFace_1_1Server_1_1Store.html", "structWebCFace_1_1Server_1_1Store" ]
      ] ],
      [ "AnonymousFunc", "classWebCFace_1_1AnonymousFunc.html", "classWebCFace_1_1AnonymousFunc" ],
      [ "Arg", "classWebCFace_1_1Common_1_1Arg.html", "classWebCFace_1_1Common_1_1Arg" ],
      [ "AsyncFuncResult", "classWebCFace_1_1AsyncFuncResult.html", "classWebCFace_1_1AsyncFuncResult" ],
      [ "Client", "classWebCFace_1_1Client.html", "classWebCFace_1_1Client" ],
      [ "ClientData", "structWebCFace_1_1ClientData.html", "structWebCFace_1_1ClientData" ],
      [ "Dict", "classWebCFace_1_1Common_1_1Dict.html", "classWebCFace_1_1Common_1_1Dict" ],
      [ "DictElement", "structWebCFace_1_1Common_1_1DictElement.html", "structWebCFace_1_1Common_1_1DictElement" ],
      [ "DictTraits", "structWebCFace_1_1Common_1_1DictTraits.html", "structWebCFace_1_1Common_1_1DictTraits" ],
      [ "DictTraits< std::shared_ptr< T > >", "structWebCFace_1_1Common_1_1DictTraits_3_01std_1_1shared__ptr_3_01T_01_4_01_4.html", "structWebCFace_1_1Common_1_1DictTraits_3_01std_1_1shared__ptr_3_01T_01_4_01_4" ],
      [ "DictTraits< VectorOpt< T > >", "structWebCFace_1_1Common_1_1DictTraits_3_01VectorOpt_3_01T_01_4_01_4.html", "structWebCFace_1_1Common_1_1DictTraits_3_01VectorOpt_3_01T_01_4_01_4" ],
      [ "EventTarget", "classWebCFace_1_1EventTarget.html", "classWebCFace_1_1EventTarget" ],
      [ "Field", "structWebCFace_1_1Field.html", "structWebCFace_1_1Field" ],
      [ "FieldBase", "structWebCFace_1_1Common_1_1FieldBase.html", "structWebCFace_1_1Common_1_1FieldBase" ],
      [ "FieldBaseComparable", "structWebCFace_1_1Common_1_1FieldBaseComparable.html", "structWebCFace_1_1Common_1_1FieldBaseComparable" ],
      [ "Func", "classWebCFace_1_1Func.html", "classWebCFace_1_1Func" ],
      [ "FuncCall", "structWebCFace_1_1Common_1_1FuncCall.html", "structWebCFace_1_1Common_1_1FuncCall" ],
      [ "FuncInfo", "structWebCFace_1_1Common_1_1FuncInfo.html", "structWebCFace_1_1Common_1_1FuncInfo" ],
      [ "FuncNotFound", "structWebCFace_1_1FuncNotFound.html", "structWebCFace_1_1FuncNotFound" ],
      [ "Log", "classWebCFace_1_1Log.html", "classWebCFace_1_1Log" ],
      [ "LoggerBuf", "classWebCFace_1_1LoggerBuf.html", "classWebCFace_1_1LoggerBuf" ],
      [ "LoggerSink", "classWebCFace_1_1LoggerSink.html", "classWebCFace_1_1LoggerSink" ],
      [ "LogLine", "structWebCFace_1_1Common_1_1LogLine.html", "structWebCFace_1_1Common_1_1LogLine" ],
      [ "Member", "classWebCFace_1_1Member.html", "classWebCFace_1_1Member" ],
      [ "Queue", "classWebCFace_1_1Common_1_1Queue.html", "classWebCFace_1_1Common_1_1Queue" ],
      [ "Text", "classWebCFace_1_1Text.html", "classWebCFace_1_1Text" ],
      [ "ValAdaptor", "classWebCFace_1_1Common_1_1ValAdaptor.html", "classWebCFace_1_1Common_1_1ValAdaptor" ],
      [ "Value", "classWebCFace_1_1Value.html", "classWebCFace_1_1Value" ],
      [ "VectorOpt", "structWebCFace_1_1Common_1_1VectorOpt.html", "structWebCFace_1_1Common_1_1VectorOpt" ],
      [ "View", "classWebCFace_1_1View.html", "classWebCFace_1_1View" ],
      [ "ViewBuf", "classWebCFace_1_1ViewBuf.html", "classWebCFace_1_1ViewBuf" ],
      [ "ViewComponent", "classWebCFace_1_1ViewComponent.html", "classWebCFace_1_1ViewComponent" ],
      [ "ViewComponentBase", "structWebCFace_1_1Common_1_1ViewComponentBase.html", "structWebCFace_1_1Common_1_1ViewComponentBase" ]
    ] ],
    [ "A", "classA.html", "classA" ],
    [ "Afterdoc_Test", "classAfterdoc__Test.html", "classAfterdoc__Test" ],
    [ "Autolink_Test", "classAutolink__Test.html", "classAutolink__Test" ],
    [ "B", "classB.html", "classB" ],
    [ "C", "classC.html", "classC" ],
    [ "C1", "classC1.html", null ],
    [ "C2", "classC2.html", null ],
    [ "C3", "classC3.html", null ],
    [ "C4", "classC4.html", null ],
    [ "C5", "classC5.html", null ],
    [ "Car", "structCar.html", "structCar" ],
    [ "CoordStruct", "structCoordStruct.html", "structCoordStruct" ],
    [ "D", "classD.html", "classD" ],
    [ "E", "classE.html", "classE" ],
    [ "Enum_Test", "classEnum__Test.html", "classEnum__Test" ],
    [ "Example_Test", "classExample__Test.html", "classExample__Test" ],
    [ "Fn_Test", "classFn__Test.html", "classFn__Test" ],
    [ "Include_Test", "classInclude__Test.html", "classInclude__Test" ],
    [ "Javadoc_Test", "classJavadoc__Test.html", "classJavadoc__Test" ],
    [ "Memgrp_Test", "classMemgrp__Test.html", "classMemgrp__Test" ],
    [ "mux_using_with", "classmux__using__with.html", "classmux__using__with" ],
    [ "Object", "structObject.html", null ],
    [ "Overload_Test", "classOverload__Test.html", "classOverload__Test" ],
    [ "Par_Test", "classPar__Test.html", null ],
    [ "QTstyle_Test", "classQTstyle__Test.html", "classQTstyle__Test" ],
    [ "SomeNiceClass", "classSomeNiceClass.html", null ],
    [ "String", "classString.html", "classString" ],
    [ "Tag", "classTag.html", "classTag" ],
    [ "Test", "classTest.html", "classTest" ],
    [ "Test< T * >", "classTest_3_01T_01_5_01_4.html", "classTest_3_01T_01_5_01_4" ],
    [ "Test< void *, 200 >", "classTest_3_01void_01_5_00_01200_01_4.html", "classTest_3_01void_01_5_00_01200_01_4" ],
    [ "Truck", "structTruck.html", "structTruck" ],
    [ "Vehicle", "structVehicle.html", "structVehicle" ]
];