var searchData=
[
  ['scopedsynclock_0',['ScopedSyncLock',['../classwebcface_1_1internal_1_1ClientData_1_1ScopedSyncLock.html',1,'webcface::internal::ClientData']]],
  ['scopedunlock_1',['ScopedUnlock',['../structwebcface_1_1ScopedUnlock.html',1,'webcface']]],
  ['scopedwslock_2',['ScopedWsLock',['../classwebcface_1_1internal_1_1ClientData_1_1ScopedWsLock.html',1,'webcface::internal::ClientData']]],
  ['server_3',['Server',['../classwebcface_1_1server_1_1Server.html',1,'webcface::server']]],
  ['serverstorage_4',['ServerStorage',['../classwebcface_1_1server_1_1ServerStorage.html',1,'webcface::server']]],
  ['sharedstring_5',['SharedString',['../classwebcface_1_1encoding_1_1SharedString.html',1,'SharedString'],['../classwebcface_1_1encoding_1_1SharedString.html',1,'SharedString']]],
  ['sharedstringdata_6',['SharedStringData',['../structwebcface_1_1internal_1_1SharedStringData.html',1,'webcface::internal']]],
  ['size_7',['Size',['../classwebcface_1_1Size.html',1,'webcface']]],
  ['sizeoption_8',['SizeOption',['../classwebcface_1_1SizeOption.html',1,'webcface']]],
  ['sphere_9',['Sphere',['../structwebcface_1_1components_1_1geometries_1_1Sphere.html',1,'Sphere'],['../structwebcface_1_1components_1_1geometries_1_1Sphere.html',1,'Sphere'],['../structwebcface_1_1components_1_1geometries_1_1Sphere.html',1,'Sphere']]],
  ['sync_10',['Sync',['../structwebcface_1_1message_1_1Sync.html',1,'webcface::message']]],
  ['syncdatastore1_11',['SyncDataStore1',['../classwebcface_1_1internal_1_1SyncDataStore1.html',1,'webcface::internal']]],
  ['syncdatastore1_3c_20std_3a_3achrono_3a_3asystem_5fclock_3a_3atime_5fpoint_20_3e_12',['SyncDataStore1&lt; std::chrono::system_clock::time_point &gt;',['../classwebcface_1_1internal_1_1SyncDataStore1.html',1,'webcface::internal']]],
  ['syncdatastore1_3c_20std_3a_3ashared_5fptr_3c_20std_3a_3adeque_3c_20webcface_3a_3aloglinedata_20_3e_20_3e_20_3e_13',['SyncDataStore1&lt; std::shared_ptr&lt; std::deque&lt; webcface::LogLineData &gt; &gt; &gt;',['../classwebcface_1_1internal_1_1SyncDataStore1.html',1,'webcface::internal']]],
  ['syncdatastore2_14',['SyncDataStore2',['../classwebcface_1_1internal_1_1SyncDataStore2.html',1,'webcface::internal']]],
  ['syncdatastore2_3c_20canvas2ddata_20_3e_15',['SyncDataStore2&lt; Canvas2DData &gt;',['../classwebcface_1_1internal_1_1SyncDataStore2.html',1,'webcface::internal']]],
  ['syncdatastore2_3c_20canvas3ddata_20_3e_16',['SyncDataStore2&lt; Canvas3DData &gt;',['../classwebcface_1_1internal_1_1SyncDataStore2.html',1,'webcface::internal']]],
  ['syncdatastore2_3c_20funcdata_20_3e_17',['SyncDataStore2&lt; FuncData &gt;',['../classwebcface_1_1internal_1_1SyncDataStore2.html',1,'webcface::internal']]],
  ['syncdatastore2_3c_20robotmodeldata_20_3e_18',['SyncDataStore2&lt; RobotModelData &gt;',['../classwebcface_1_1internal_1_1SyncDataStore2.html',1,'webcface::internal']]],
  ['syncdatastore2_3c_20textdata_20_3e_19',['SyncDataStore2&lt; TextData &gt;',['../classwebcface_1_1internal_1_1SyncDataStore2.html',1,'webcface::internal']]],
  ['syncdatastore2_3c_20valuedata_20_3e_20',['SyncDataStore2&lt; ValueData &gt;',['../classwebcface_1_1internal_1_1SyncDataStore2.html',1,'webcface::internal']]],
  ['syncdatastore2_3c_20viewdata_20_3e_21',['SyncDataStore2&lt; ViewData &gt;',['../classwebcface_1_1internal_1_1SyncDataStore2.html',1,'webcface::internal']]],
  ['syncdatastore2_3c_20webcface_3a_3aimageframe_2c_20webcface_3a_3amessage_3a_3aimagereq_20_3e_22',['SyncDataStore2&lt; webcface::ImageFrame, webcface::message::ImageReq &gt;',['../classwebcface_1_1internal_1_1SyncDataStore2.html',1,'webcface::internal']]],
  ['syncinit_23',['SyncInit',['../structwebcface_1_1message_1_1SyncInit.html',1,'webcface::message']]],
  ['syncinitend_24',['SyncInitEnd',['../structwebcface_1_1message_1_1SyncInitEnd.html',1,'webcface::message']]],
  ['syncmutexeddata_25',['SyncMutexedData',['../structwebcface_1_1internal_1_1ClientData_1_1SyncMutexedData.html',1,'webcface::internal::ClientData']]]
];
