#pragma once
#include "common/val.h"
#include "common/func.h"
#include "event_key.h"
#include "member.h"
#include "func_result.h"
#include "client_data.h"
// ClientDataに対して具体的になにかする場合はこれの下
#include "event.h"
#include "data.h"
#include "func.h"
#include "client.h"
