# magickppなどビルドするプロセスに渡す引数を初期化
unset(WEBCFACE_FLAGS)
unset(WEBCFACE_LDFLAGS)
unset(WEBCFACE_CMAKE_PROPS)

list(APPEND WEBCFACE_FLAGS -O3)
list(APPEND WEBCFACE_CMAKE_PROPS "-DCMAKE_BUILD_TYPE=Release")

if(WEBCFACE_PIC)
    list(APPEND WEBCFACE_FLAGS -fPIC)
endif()
list(APPEND WEBCFACE_CMAKE_PROPS "-DCMAKE_POSITION_INDEPENDENT_CODE=${WEBCFACE_PIC}")

foreach(arch IN LISTS CMAKE_OSX_ARCHITECTURES)
    list(APPEND WEBCFACE_FLAGS -arch ${arch})
    list(APPEND WEBCFACE_LDFLAGS -arch ${arch})
endforeach()
list(JOIN CMAKE_OSX_ARCHITECTURES "\;" CMAKE_OSX_ARCHITECTURES_S)
list(APPEND WEBCFACE_CMAKE_PROPS "-DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES_S}")

list(JOIN CMAKE_PREFIX_PATH_S "\;" CMAKE_PREFIX_PATH_S)
list(APPEND WEBCFACE_CMAKE_PROPS "-DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH_S}")
list(JOIN WEBCFACE_FLAGS " " WEBCFACE_FLAGS)
list(JOIN WEBCFACE_LDFLAGS " " WEBCFACE_LDFLAGS)
