enable_testing()
file(GLOB TEST_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/src/test/*.cpp)
foreach(TEST_FILE IN LISTS TEST_SOURCES)
    get_filename_component(TEST_TARGET ${TEST_FILE} NAME_WE)
    # message("new test: ${TEST_TARGET}")
    set(TEST_NAME "test_${TEST_TARGET}")
    add_executable(${TEST_NAME} ${TEST_FILE})
    target_link_libraries(${TEST_NAME} webcface)
    add_test(NAME run_${TEST_NAME} COMMAND ${TEST_NAME})
endforeach()