name: CMake Test (Linux GCC)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  test-linux-gcc:
    strategy:
      matrix:
        dep: ["apt", "source", "static"]
        include:
        - dep: apt
          shared_flag: on
        - dep: source
          shared_flag: on
        - dep: static
          shared_flag: off
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-10 g++-10
        if [ ${{matrix.dep}} = apt ]; then sudo apt-get install -y libspdlog-dev libmagick++-dev libopencv-dev; fi

    - name: Configure CMake
      env:
        CC: gcc-10
        CXX: g++-10
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DWEBCFACE_TEST=on
        -DWEBCFACE_EXAMPLE=on
        -DWEBCFACE_TEST_TIMEOUT=200
        -DWEBCFACE_SHARED=${{matrix.shared_flag}}
        -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/install

    - name: Build
      run: cmake --build build -t install

    - name: Test
      env:
        WEBCFACE_TRACE: 1
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure --timeout 20

    - name: Test CMake with installed package
      working-directory: ${{github.workspace}}/.github/test
      env:
        CC: gcc-10
        CXX: g++-10
      run: |
        cmake -B build -DCMAKE_PREFIX_PATH=${{github.workspace}}/build/install
        cmake --build build

    - name: Test building with pkg-config
      working-directory: ${{github.workspace}}/.github/test
      env:
        PKG_CONFIG_PATH: ${{github.workspace}}/build/install/lib/pkgconfig
      run: |
        g++-10 test.cpp $(pkg-config --cflags --libs webcface)
        gcc-10 test.c $(pkg-config --cflags --libs webcface) -lstdc++

