name: CMake Test (MacOS Clang)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  test-macos-clang:
    strategy:
      matrix:
        dep: ["brew", "source"]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Homebrew
      if: matrix.dep == 'brew'
      run: brew update --preinstall
    - name: Install Homebrew dependencies
      if: matrix.dep == 'brew'
      run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install spdlog msgpack-cxx || true

    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DWEBCFACE_TEST=on
        -DWEBCFACE_EXAMPLE=on
        -DWEBCFACE_TEST_TIMEOUT=1000

    - name: Build
      run: cmake --build build

    - name: Test
      env:
        WEBCFACE_TRACE: 1
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure --timeout 15
