name: CMake Test (Windows MSVC)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  test-windows-msvc:
    strategy:
      matrix:
        use_opencv: [on, off]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "recursive"
    - name: Install dependencies
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install -y opencv
    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DWEBCFACE_TEST=on
        -DWEBCFACE_EXAMPLE=on
        -DWEBCFACE_TEST_TIMEOUT=1000
        -DWEBCFACE_USE_OPENCV=${{matrix.use_opencv}}
        -DCMAKE_PREFIX_PATH=$Env:OPENCV_DIR

    - name: Build
      run: cmake --build build

    - name: Test
      env:
        WEBCFACE_TRACE: 1
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure --timeout 15
