name: CMake Test (MacOS Clang)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  test-macos-clang:
    strategy:
      matrix:
        dep: ["brew-opencv", "brew", "source"]
        include:
        - dep: brew-opencv
          use_opencv: on
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Homebrew dependencies
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
      run: |
        brew update --preinstall
        if [ ${{matrix.dep}} = brew ]; then brew install spdlog msgpack-cxx || true; fi
        if [ ${{matrix.dep}} = brew-opencv ]; then brew install spdlog msgpack-cxx opencv || true; fi

    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DWEBCFACE_TEST=on
        -DWEBCFACE_EXAMPLE=on
        -DWEBCFACE_TEST_TIMEOUT=1000
        -DWEBCFACE_USE_OPENCV=${{matrix.use_opencv}}

    - name: Build
      run: cmake --build build

    - name: Test
      env:
        WEBCFACE_TRACE: 1
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure --timeout 30
