name: CMake Test (Linux GCC)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  test-linux-gcc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "recursive"

    - name: Configure CMake
      env:
        CC: gcc
        CXX: g++
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DWEBCFACE_TEST=on
        -DWEBCFACE_EXAMPLE=on
        -DWEBCFACE_TEST_TIMEOUT=50

    - name: Build
      run: cmake --build build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure --timeout 5
