name: CMake Test (MacOS Clang)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  test-macos-clang:
    strategy:
      matrix:
        dep: ["brew", "source", "submodule", "static", "framework"]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: git submodule update --init
      if: matrix.dep == 'submodule'

    - name: Install Homebrew dependencies
      if: matrix.dep == 'brew'
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
      run: |
        brew update --preinstall
        brew tap na-trium-144/webcface
        brew install spdlog msgpack-cxx cli11 utf8cpp googletest opencv na-trium-144/webcface/imagemagick-no-openmp na-trium-144/webcface/curl-ws na-trium-144/webcface/crow-unix-socket || true
    - name: Install Nasm
      if: matrix.dep == 'framework'
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
      run: |
        brew update --preinstall
        brew install nasm

    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DWEBCFACE_TEST=on
        -DWEBCFACE_EXAMPLE=on
        -DWEBCFACE_TEST_TIMEOUT=1000
        "-DWEBCFACE_SHARED=$([[ ${{matrix.dep}} = static ]]; echo $?)"
        "-DWEBCFACE_FIND_OPENCV=$([[ ${{matrix.dep}} != brew ]]; echo $?)"
        -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/install
        "-DCMAKE_PREFIX_PATH=$(brew --prefix)/opt/imagemagick-no-openmp;$(brew --prefix)/opt/curl-ws;$(brew --prefix)/opt/crow-unix-socket"
        "-DWEBCFACE_FRAMEWORK=$([[ ${{matrix.dep}} != framework ]]; echo $?)"
        "-DWEBCFACE_FIND_LIBS=$([[ ${{matrix.dep}} = submodule || ${{matrix.dep}} = static || ${{matrix.dep}} = framework ]]; echo $?)"
        "-DCMAKE_OSX_ARCHITECTURES=$([[ ${{matrix.dep}} = framework ]] && echo 'arm64;x86_64')"

    - name: Build
      run: cmake --build build -t install

    - name: Test
      env:
        WEBCFACE_TRACE: 1
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure --timeout 100

    - name: Check Exported Symbol
      if: matrix.dep == 'submodule'
      run: |
        bash -c "! nm -g --defined-only build/libwebcface.dylib | grep -v webcface | grep -v wcf | grep -v St"
        bash -c "! nm -g --defined-only build/libwebcface.dylib | grep -v webcface | grep -v wcf | grep spdlog"
        bash -c "! nm -g --defined-only build/libwebcface.dylib | grep -v webcface | grep -v wcf | grep crow"
        bash -c "! nm -g --defined-only build/libwebcface.dylib | grep -v webcface | grep -v wcf | grep asio"
        bash -c "! nm -g --defined-only build/libwebcface.dylib | grep -v webcface | grep -v wcf | grep utf8"

    - name: Test CMake with installed package
      working-directory: ${{github.workspace}}/.github/test
      run: |
        cmake -B build -DCMAKE_PREFIX_PATH=${{github.workspace}}/build/install
        cmake --build build

    - name: Test building with pkg-config
      if: matrix.dep != 'framework'
      working-directory: ${{github.workspace}}/.github/test
      env:
        PKG_CONFIG_PATH: ${{github.workspace}}/build/install/lib/pkgconfig
      run: |
        pkg-config --cflags --libs webcface
        clang++ -std=c++17 test.cc $(pkg-config --cflags --libs webcface)
        clang -std=c99 test.c $(pkg-config --cflags --libs webcface) -lc++

    - name: Test building using framework
      if: matrix.dep == 'framework'
      working-directory: ${{github.workspace}}/.github/test
      run: |
        clang++ -std=c++17 test.cc -F${{github.workspace}}/build/install/Frameworks -framework webcface
        clang -std=c99 test.c -F${{github.workspace}}/build/install/Frameworks -framework webcface
