name: CMake Test (Linux GCC)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  test-linux-gcc:
    strategy:
      matrix:
        use_opencv: [on, off]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "recursive"
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc-10 g++-10 libopencv-dev
    - name: Configure CMake
      env:
        CC: gcc-10
        CXX: g++-10
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DWEBCFACE_TEST=on
        -DWEBCFACE_EXAMPLE=on
        -DWEBCFACE_TEST_TIMEOUT=50
        -DWEBCFACE_USE_OPENCV=${{matrix.use_opencv}}

    - name: Build
      run: cmake --build build

    - name: Test
      env:
        WEBCFACE_TRACE: 1
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure --timeout 5
