name: Meson Test (Linux Clang) and Clang-Tidy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

jobs:
  test-linux-clang:
    strategy:
      matrix:
        dep: ["apt", "source"]
        clang: [7, 13, 15, 17]
        include:
        - os: ubuntu-20.04
          clang: 7
        - os: ubuntu-20.04
          clang: 13
        - os: ubuntu-22.04
          clang: 15
        - os: ubuntu-24.04
          clang: 17

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    # - run: git submodule update --init
    #   if: matrix.dep == 'submodule'
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build
        if [[ ${{matrix.dep}} = apt ]]; then sudo apt-get install -y libspdlog-dev libvips-dev libopencv-dev; fi
        if [[ ${{matrix.dep}} = apt ]] && [[ ${{matrix.os}} = ubuntu-22.04 ]]; then sudo apt-get install -y libcli11-dev; fi
        if [[ ${{matrix.dep}} = apt ]] && [[ ${{matrix.os}} = ubuntu-24.04 ]]; then sudo apt-get install -y libcli11-dev libmsgpack-cxx-dev; fi
    - name: Install meson
      run: pip install meson || pip install --break-system-packages meson
    - name: Install clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "${{matrix.clang}}"
    - name: Setup Meson
      env:
        CC: ${{ env.LLVM_PATH }}/bin/clang
        CXX: ${{ env.LLVM_PATH }}/bin/clang++
      run: >
        meson setup build
        --buildtype=debug
        $([[ ${{matrix.dep}} != apt ]] && echo "-Dwrap_mode=forcefallback")
        -Dtest_wait=200
        "-Dforce_fallback_for=['libcurl']"
    - name: Compile
      run: meson compile -C build || meson compile -C build
    - name: Test
      run: meson test -C build --print-errorlog --suite webcface
    - name: clang-tidy
      if: matrix.clang == '17' && matrix.dep == 'apt'
      run: python3 scripts/clang-tidy.py 4
    # - name: clang-format-check
    #   if: matrix.clang == '17' && matrix.dep == 'apt'
    #   run: ninja clang-format-check -Cbuild
