name: CMake Test (Linux Clang) and Clang-Tidy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  test-linux-clang:
    strategy:
      matrix:
        dep: ["apt", "submodule"]
        clang: [7, 13, 15, 17]
        include:
        - os: ubuntu-20.04
          clang: 7
        - os: ubuntu-20.04
          clang: 13
        - os: ubuntu-22.04
          clang: 15
        - os: ubuntu-22.04
          clang: 17

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - run: git submodule update --init
      if: matrix.dep == 'submodule'
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        if [ ${{matrix.dep}} = apt ]; then sudo apt-get install -y libspdlog-dev libjpeg-dev libpng-dev libwebp-dev; fi
    - name: Install clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "${{matrix.clang}}"
    - name: Configure CMake
      env:
        CC: ${{ env.LLVM_PATH }}/bin/clang
        CXX: ${{ env.LLVM_PATH }}/bin/clang++
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DWEBCFACE_TEST=on
        -DWEBCFACE_EXAMPLE=on
        -DWEBCFACE_TEST_TIMEOUT=200
        -DWEBCFACE_CLANG_TIDY=${{env.LLVM_PATH}}/bin/clang-tidy

    - name: Build
      run: cmake --build build

    - name: Test
      env:
        WEBCFACE_TRACE: 1
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure --timeout 20
