name: Meson Test (Linux Nix)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

jobs:
  test-linux-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@master
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    # - uses: cachix/cachix-action@master
    #   with:
    #     name: mycache
    #     signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build --arg doCheck true
