name: CMake Test (Linux GCC)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  test-linux-gcc:
    strategy:
      matrix:
        dep: ["apt", "submodule"]
        os: ["ubuntu-20.04", "ubuntu-22.04", "ubuntu-24.04"]
        include:
        - os: ubuntu-20.04
          gcc_ver: 10
        - os: ubuntu-22.04
          gcc_ver: 11
        - os: ubuntu-24.04
          gcc_ver: 13
        - dep: static
          os: ubuntu-20.04
          gcc_ver: 10
        - dep: source # dep=submoduleと役割が被っている
          os: ubuntu-20.04
          gcc_ver: 10
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - run: git submodule update --init
      if: matrix.dep == 'submodule'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-${{matrix.gcc_ver}} g++-${{matrix.gcc_ver}}
        if [ ${{matrix.dep}} = apt ]; then sudo apt-get install -y libspdlog-dev libjpeg-dev libpng-dev libwebp-dev libopencv-dev; fi

    - name: Configure CMake
      env:
        CC: gcc-${{matrix.gcc_ver}}
        CXX: g++-${{matrix.gcc_ver}}
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DWEBCFACE_TEST=on
        -DWEBCFACE_EXAMPLE=on
        -DWEBCFACE_TEST_TIMEOUT=200
        "-DWEBCFACE_SHARED=$([[ ${{matrix.dep}} = static ]]; echo $?)"
        "-DWEBCFACE_FIND_OPENCV=$([[ ${{matrix.dep}} != apt ]]; echo $?)"
        -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/install

    - name: Build
      run: cmake --build build -t install

    - name: Test
      env:
        WEBCFACE_TRACE: 1
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure --timeout 20

    - name: Test CMake with installed package
      working-directory: ${{github.workspace}}/.github/test
      env:
        CC: gcc-${{matrix.gcc_ver}}
        CXX: g++-${{matrix.gcc_ver}}
      run: |
        cmake -B build -DCMAKE_PREFIX_PATH=${{github.workspace}}/build/install
        cmake --build build

    - name: Test building with pkg-config
      working-directory: ${{github.workspace}}/.github/test
      env:
        PKG_CONFIG_PATH: ${{github.workspace}}/build/install/lib/pkgconfig
      run: |
        g++-${{matrix.gcc_ver}} -std=c++20 test.cc $(pkg-config --cflags --libs webcface)
        gcc-${{matrix.gcc_ver}} -std=c99 test.c $(pkg-config --cflags --libs webcface) -lstdc++

