name: CMake Test (Linux Clang) and Clang-Tidy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: []

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  test-linux-clang:
    strategy:
      matrix:
        dep: ["apt-opencv", "apt", "source"]
        include:
        - dep: apt-opencv
          use_opencv: on
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        if [ ${{matrix.dep}} = apt ]; then sudo apt-get install -y libspdlog-dev; fi
        if [ ${{matrix.dep}} = apt-opencv ]; then sudo apt-get install -y libspdlog-dev libopencv-dev; fi
    - name: Install clang-13
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "13"
    - name: Configure CMake
      env:
        CC: ${{ env.LLVM_PATH }}/bin/clang
        CXX: ${{ env.LLVM_PATH }}/bin/clang++
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DWEBCFACE_TEST=on
        -DWEBCFACE_EXAMPLE=on
        -DWEBCFACE_TEST_TIMEOUT=50
        -DWEBCFACE_USE_OPENCV=${{matrix.use_opencv}}
        "-DCMAKE_CXX_CLANG_TIDY=${{env.LLVM_PATH}}/bin/clang-tidy;--header-filter=$(pwd)/src/"

    - name: Build
      run: cmake --build build

    - name: Test
      env:
        WEBCFACE_TRACE: 1
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure --timeout 5
