name: Doxygen
on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "recursive"
    - name: install graphviz
      run: sudo apt-get update && sudo apt-get install -y graphviz
    # 1.9.8で生成するとリンクがバグる。
    # 1.10以上はまだ試していない
    - uses: ssciwr/doxygen-install@v1
      with:
        version: "1.9.7"
    - name: Install ninja
      run: sudo apt-get update && sudo apt-get install -y ninja-build
    - name: Install meson
      run: pip install meson || pip install --break-system-packages meson
    - name: Setup Meson
      run: meson setup build
    - name: Generate Documentation
      run: |
        mkdir -p build/doxygen
        doxygen
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build/doxygen/html
