on:
  pull_request:
    branches: [main]
    paths: ['README.md']

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: |
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc -o gh-md-toc
          chmod a+x gh-md-toc
          ./gh-md-toc --insert --no-backup --hide-footer README.md
          rm gh-md-toc
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto update markdown TOC
